# Encrypt as credentials.sops.yaml, then add it to the PARENT kustomization.yaml.
# These are issued by "Create new runner", not the deprecated registration token.
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-credentials-1
    namespace: forgejo-runners
type: Opaque
stringData:
    uuid: ENC[AES256_GCM,data:K3y6zjfXq71K0koxlBbxwB1F4UhgZ5XrUeLhmx8zcTptDVRZ,iv:wO2ZRfZk0pNr+vnHZNDdiZUFGPqk+8RzkG5hReaoV/0=,tag:svUa3NLnSuj623stPL0eDg==,type:str]
    token: ENC[AES256_GCM,data:tCtRJQvBq1WN/Arzr7cyFY5942Iv9SDyLWKfNa6bzLMHB7vmOSXBpA==,iv:JslAX0TB9Je9rQzWyFhs7Og0Z+PXqI5iEHb0g5PWdvk=,tag:f9bMq4C2gsL4JENbMLyEIg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBra3RibysvKzBTT3MyY1pC
            cjRZMGNZQWlDbmxIU3NNZktBREhWK2s5dmtJCmZDaHJUdXhZd3ZCbk5RbVZ0RWhi
            dXI2VXlEelYvRThRRGFVb2I4VlFxTVEKLS0tICtDdndFcEVkL3FpT0N0NzRYM3lR
            K1FuOEM4cTdkcHA1Y2IyNlRjdHJrN0UK355UNK4RgRS2Lp65jnEkQ/8UBy2bpCNo
            euPVhmr2fM3EW2NKXyaJRlzCJzSHqE2fQ3APS+1JsnQ4pF/KCfLgow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16c82nw2ut3vx6jfc28vx72090wt7fluyp5m2mw68f09qf4lecefq3zn9t5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:34Z"
    mac: ENC[AES256_GCM,data:ePVJKM2DOKdWeG/W06ClEcndUu3suZc5y/wTMr/+baYdvNKOvIEwNkkdOi17VNP/Izdh9hc0cFj1GKnnc8fJcRPZzlle5jmds4SOXa4C7PlXXOzVXiL1V1Jz8DZD1FLRmRv8/EKqgVWKQ9lrs+81iNvWoE6H7VtnzCBT6wvPXXE=,iv:Fnt+uwaJ3Y9IarYYoYpDhpu090RI/Y1jmjlyTCFn54s=,tag:WEj4e5Rrbg/VFn/MJviDNQ==,type:str]
    version: 3.13.3
