apiVersion: v1
kind: Secret
metadata:
    name: synapse-postgres-user
    namespace: postgres
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:6VKJmxLzXQ==,iv:zjK9zaHfFlNxGcatdL/x1XBzo4xjRAOiixwiGVpPpdg=,tag:fNH0PnhjMYOcwVaA5p2pPQ==,type:str]
    password: ENC[AES256_GCM,data:ii8RV+mqUBFvKQ4Dstd6hPuH0thaDNURnDK7mhG5jQcMPpJUB7rAn5i6S1QaVrRX,iv:sGwhVSIkwAOowPgtYKSkarT4m4HTQ1plu3eantPIows=,tag:NA3dQXp0oCbC+NTmPECj7w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqM245dGp0UkZmck9xSHU2
            Nk81VjRKZEd2NnRIUkpEbGZzWUtBMC8xNEFjCmpVK3g1bEZiUnhWMVpXaGM3RnA2
            T1ZjK0cvOXF1ZWJadCtKeFozZWlJaTQKLS0tIFVxWm5KSTk2eC9iQ0I3VjVYQ0NE
            TThNQ2w3Ri9aQmxCSUl4bGdOMEk1TVEKKBtLYAmfJqjNAzrniroOWVg9yU5eWMio
            q86efkcB7pjBHKZ/jQGG9wbX6TiaesSXNKYX5PFWYVgVxhSUgwAnpw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16c82nw2ut3vx6jfc28vx72090wt7fluyp5m2mw68f09qf4lecefq3zn9t5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-02T20:15:42Z"
    mac: ENC[AES256_GCM,data:ONp8qfEZ/1ajidA/rDG+J+1GFobfsOdfM9bECsvWejqoT/TXrkMRhMlOrDvDcQWf+Om9VzDRiiUPpcCPyLQZAHFts5DpL/L1OshEtMJd68jjLxkqGmWdSjJMjAElmget2QQzFYVllcQ18IMDizdAFNvL6tMwfYUbkBNqNI00FKA=,iv:7FMzkXAkLKxbwrlkbrHpXgpnApvF1Jf7oY7mWYLpyvU=,tag:BSUKeL011irItIZ14Yd8WA==,type:str]
    version: 3.13.3
