apiVersion: v1
kind: Secret
metadata:
    name: synapse-postgres-user
    namespace: postgres
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
data:
    username: ENC[AES256_GCM,data:qfm7mjjivQ==,iv:cKHOFX0POVctf4tqNzCuog0P6v1M9YotHQWr8pKzJcM=,tag:TxaGGG0NhRv4hpneSm8AmA==,type:str]
    password: ENC[AES256_GCM,data:fGWA5wKrdcR5e7E4fGUYtCqd87u0KYb+MMWkjdfFvbRid0t46xTARtq8Dc3e6Li5,iv:QVcIwASFtAVjBNreVLogqlpLu/vUytkXy0YgEFRQCY8=,tag:wo1DR6wvjUrbPasW7Cffgw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NmlSWE9TclQ1eHFCZkMy
            eWlKMml1WTJwbzFTYUF6RXFKSWRpbVFvalVFCmZ6R09kZXJOSFBOckh5a3VjUGYz
            R2FVNlFLd3pJN256SzFvYkk0czc2bk0KLS0tIDUyd3B1SWFudWgzWVN6MFBqcXhh
            eGRQOGpTZGtPQ3UweEw4VG5vRFRzN00KiY2VjTFk96oDjcVizROlrm3sYCMTxcab
            T+jB6rqfnNqVe/nz/voizHMI3KPG5LHT3TJntYNqqnAe20ZX42vFnw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16c82nw2ut3vx6jfc28vx72090wt7fluyp5m2mw68f09qf4lecefq3zn9t5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-02T20:12:00Z"
    mac: ENC[AES256_GCM,data:mTzxfUwETmKWUt30pfPe+zyoTD4MnGJVnzNecFwhZLyOCpzE067HdZkCA2aF0wxlArr6OwzF+Oec5t8GrehwVndFz5wcxrcjDqX+5wwiSzr6PJoQ84prrb1SZL6L5VkQ52CbtifuKu55BzxiUxSYn/zKJ+8eBiy6kd81Fr9DTlg=,iv:xi3iWN2Q677H4JsWgRa5oKVO2oi+2OziFnCii6l1ZzY=,tag:JyUrnpsx1GLkS6neFsfWDg==,type:str]
    version: 3.13.3
