apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synapse-media
  namespace: synapse
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-r2
  resources:
    requests:
      storage: 30Gi
