apiVersion: v1
kind: Secret
metadata:
    name: synapse-secrets
    namespace: synapse
type: Opaque
stringData:
    database-password: ENC[AES256_GCM,data:a02XMHSUdGB99U77GBd6rvg6lSuTnqSVXA/BKjX1BzrMXymgTCc12JLJVGgmLN+5,iv:SlcbIjTaVlyiwO0VUXQ6peZcRyBSj+NQJANmF5qQDtI=,tag:5PeAK/CJM56HGLRDHoFdBQ==,type:str]
    registration-shared-secret: ENC[AES256_GCM,data:qNkYlQE4oArQ9g3Wu403qKyfLkn7mp9ug6lcnQfxPhjZ8r03HWsp8du9nNYjF9fiAR+6PgoZ33DgjObo0u5YEw==,iv:7Op6hlfwcqLdSZM5xmOD7mgPud88fLbxa0nRPoWIX3o=,tag:C+ZSOP30l/5E4+us/mea+g==,type:str]
    macaroon-secret-key: ENC[AES256_GCM,data:KFjyBMkoTYx/+D2w6PS4aWGJHhamQEW7WEVwYKn/rm7GNzEMXWerlIYnReChgt/LGK2+wDSJCIaAPEe87wyNZQ==,iv:hcE+KZzaUznqU911mPD2d8gnnURLw7CCfhcAwmaxVPQ=,tag:P7b39XUK4GgIIweAMBdJEQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOcm52WGRsZ0NkUWZjRm5W
            VmUrZjlBTmsrNnVEOXkzUlVuejliMEtBQngwCkRxLytzVjZ3U1Zib2tQcXdqc3Fi
            QnI1UWhCM0NKeXp3ZTIzUW5OeU9rVDQKLS0tIGk0bjl4ZUwrTDUxcUN6T285ckJ5
            bnlWY2ZnM0Z3M0E4MUZlTWZ0emRMSWcKomT/GJb5k5jH7aUvCkLiDrzE4n6th4xd
            AhbSJ1vxzlG0kqpRGsv/gsBI7/Lhh0v6spOAo2+fEQ9UujRZC3H/OQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16c82nw2ut3vx6jfc28vx72090wt7fluyp5m2mw68f09qf4lecefq3zn9t5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-02T20:21:25Z"
    mac: ENC[AES256_GCM,data:WkERnCiMAJ+tvfx8jyFh22bcPpHYPgYiCOPNkb6T7G5BYue3dsWRiYNsN15bOdbYxHWMnrp8d22Is//A9ff6ULST9yhdpGKSuajTB1XfcyDr4xFwrP2zm+b2QuOVPcrocwu/8kcs0jBx9eZVdhqdQMo8KEqdxW5z1phQNx3+cbQ=,iv:0YzPjQZYzt02hfYcFw81rqH/rKESHQb7E0YBskUTq8k=,tag:d5qP70AXWYOuizzsg9/GIw==,type:str]
    version: 3.13.3
