apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:78DnjTyO2JTUUmLGMIyS3zFXlr5B7sxUUxSaRzdDd6TQK5wFNos2LKc0VFT6IlIIaDKNEm5KlwHQsFYVgicBUQ==,iv:hJV+dl1mizhmbcoMG60daPUptQScaZoFFrq/CPC3Py4=,tag:1Y1SwMSRWLT8WQLyDJ+3QQ==,type:str]
    admin-user: ENC[AES256_GCM,data:qFQS66Gs3uM=,iv:V5JV+saAyvLDgwsb3fcfxnMjN7d/cGg/eBgFMHby32o=,tag:HWrYSOmfU8N+0LqPki+WqA==,type:str]
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4MjBPN01kWlVxZU0yajg5
            WC9wTi95UnBhVmpPam5sMENGV05OYnMxK0hBCjZsemIrQXphdFJCVmNXVVRZa3VL
            VDRtdWJuSzlRUzV1RVovOXc1eTFDN28KLS0tIEkwc3gxeDBtL1dqTlo1cG0zSndJ
            T1RMdC9wTENTSWxNdDRCZ05oaXk1MjgK3aYYmzAYTrwGE5zc91+UhuIsy09vpdW+
            FkwgqO8NwOu2DTBam+TMgLfeQU8dBYKako+epY67TtzTt74j92nN0g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16c82nw2ut3vx6jfc28vx72090wt7fluyp5m2mw68f09qf4lecefq3zn9t5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-02T19:45:57Z"
    mac: ENC[AES256_GCM,data:APfuA5YPZe+et99UO6ZRSf/z+3qE7eBSAXMDLwk2hve/9RZ9dMgf0LPB6DR63EGf3XjVaD5oohgBL7Q1gEfxbrq0x5naYMyaLuAODiz7BuWHVau+SRu4Ny/NvqPQrA23CoO3bUfVa3/WdZLqqGalAtNqJnKx8fQvTW3wILbWgI0=,iv:ahd5MPxn/1Ko+eWz56hKRbveN5LCUxbR0as8xwf1zik=,tag:QlX56pAUWYWtanLv1lgm3A==,type:str]
    version: 3.13.3
