apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:fb1SqyKABl/WNcBzQCb6FYu+xMTx7j1qXLwMdKPXwmjXhvbmW2TYn7JL6f/FCn31zNnoE8ENuXj9V68YIbtvuQ==,iv:Jh7lzwfEOtY4qopaVp4uE8uEfj/miX8OS0G2ss6LPHg=,tag:E7wmsKOgp7VYj549d7N1fw==,type:str]
    admin-user: ENC[AES256_GCM,data:M91qlyvEFqQ=,iv:w0jxcorEOZUgdMAMROi8tjrtj9KOcQtaVKDzp3Ynuuk=,tag:C6SiF9unSPbRjDLah5mPkA==,type:str]
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYb3I1OWtqWFJmMDQ4dDQ3
            aFhkbkNPVy8vQktyMzVtZ2JhYkltS0FkWlZZCnRTa2pobmJUdW5NQnZ1TlN2U1ZO
            dUYwUW8rNzc4ZTRWVkR4YWoxNHJNRVUKLS0tIEh6ci9ZY3cxc2xMWjFYOTJPeWtB
            TTEvN2pITE84L0M2UUMvc0lNWkJOTUUKOh/kGPwT2zeXlxioXYEUzb5wX7XMny0x
            mRfdOkI5SymZwsEh185t8JkWgVfWW647qsBbIgFSvUfZbsQTsLSQ0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16c82nw2ut3vx6jfc28vx72090wt7fluyp5m2mw68f09qf4lecefq3zn9t5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-29T19:33:11Z"
    mac: ENC[AES256_GCM,data:8/6Tg6VP7HLXPklP+MI5SakGe5A//b1wT/jzQf6xsIx/1a39GN1TT4GlxcIMemDDHuALTFJX/TPBYvfhPorYQN6G6HWhoNL5K7jtXosDUKVgi6PEeeIUa6eSYfrKlwczLD68bQwsib52Eo0u1KoXH7/jVo7cK22HhTYesbwwSeo=,iv:0bN/ElFIyGkoqhGCig7ffRx1vUk3W39BtN2L9C/ZdqY=,tag:4ABz7yyOdLAx4pvpyZS7Ig==,type:str]
    version: 3.13.3
