apiVersion: v1
data:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:kJVuv4jUBm232A1fi1l7b0tFftmamtnxS/rp7xcGxlAwIj31K7rW6a8dz/Lm147ZQn5Z34LBM5CpBYmlPxIdxVBpSMRD13hg5fTL8YhkVZAk3sWDh8TtPiMaIWU4vCefxT8PKBxyr7KxI0HXd9ZBq1q0ORjUtx9hHklAtPXCse8yNIvAjEJ5mW+L5N7rWletSYo5/7uUUd647lX47XZo8ROL1V0XVIKDbzUtVQH+Ne0eCovfWhzKb8J1oaWj+N68PMMMWRW8DLR7SI8mFWV9pVFnpPQyXrJOzX0O2uTM69G2SZmm2mE2cN2umwZHPwyUv7LT0UMGg0I=,iv:8H9dj36AkjeFYvFj7//30r/lkcSgQuH5TFdmXQF23FQ=,tag:4bfbm8TKRLyVPLd8KoRtcg==,type:str]
kind: Secret
metadata:
    name: cloudflared-token
    namespace: cloudflare
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSDhYWnhmMmNseEo1dlBt
            VXFBQzB5c09ib09PZXRCWFFzQnMxRTZZYVZNCmNyamZVekt0ZU1WaW9FdERPdmk5
            Y3dSQU43Z0dZakxGQmJuM1Jsa1NXUjgKLS0tIGhhQU0xV1FYVDRFNnpJMXRJR0Iv
            dXRWZFJtcEkySFlZLzUvYXhhOWE0TkUKSY5v8+EVBziwp1RWO48WBGo53KdqSxdn
            bTZiBvYS8jvoLRoGwChsOYNIjz337I7iRU2VF7V40lQgcr05kvbWMA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16c82nw2ut3vx6jfc28vx72090wt7fluyp5m2mw68f09qf4lecefq3zn9t5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-25T20:37:33Z"
    mac: ENC[AES256_GCM,data:LyUN50zYCqWXe9jypobfzOiBt7o5HoMsLmudgds1gxSbQSNDWhy5zBVsKSLIbF91PrLL0FpJhYWSdX3LP7qjF/vsFj7bR+PWnKm3VEdhbN1xLDG6JxRnEU+T23YUGh4RSjbPi0Co4uOej7W36wBQ9GdSXkqXdL8oWzyqdTT9xeU=,iv:JWI91WywlMYVRpZXDPYyWbPdgXYeMMQ2J0aNTETX3AQ=,tag:ygQqdDckYBvhbSfnH6XY5A==,type:str]
    version: 3.13.3
