# Encrypt as credentials.sops.yaml, then add it to the PARENT kustomization.yaml.
# These are issued by "Create new runner", not the deprecated registration token.
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-credentials-2
    namespace: forgejo-runners
type: Opaque
stringData:
    uuid: ENC[AES256_GCM,data:a2db+Dg+eLyDjuAYPq3Fw9EuktM3LP0mUPW9wO0mjGyq3usU,iv:G8yJ7Yw9saPXw/RRexsU8llJkOlR9w4/qLFtATULIlI=,tag:qjZjSEfKPqtoQfhB+rKKNA==,type:str]
    token: ENC[AES256_GCM,data:fOPitkYwrScs5ucrMSyv+Q24hcMIwkgHYWFuWtN+Grpz9UXddmiJHg==,iv:Anp9l9vJBdXeeR+VpRBs6qS5v/J0TPH8JfOgy4O+6o0=,tag:w98edHV1TiN8S9tsPJ4JEw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIU0c5eUlGZjFPeVZMYnRh
            V1hHZ3kwWHExVlNSNmJCaFJEMG1HeVBkTVZZCm1IQXo4blRHSC85Ry9ReGJOdzBy
            YjhVZHh4amtiZ1psaXN6S1llQmtvNk0KLS0tIEpRaGtYQnpWbVpkZ2FNV0RURzhN
            RW9qLzV2VWdEYWZnSEJ1bXR1bFpmOUUKL1EeR+HO5GYLOc6rhkm83s1qx5dTMZwK
            rNZZnZCAN7qzj9fQhH8zIWl1RJV5vlMSqmcquKH1RBMYu8J+451suQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16c82nw2ut3vx6jfc28vx72090wt7fluyp5m2mw68f09qf4lecefq3zn9t5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:38Z"
    mac: ENC[AES256_GCM,data:VPhIOi0qHblB3bMhaHrtHJ+NyQqg6uHAB5wxHWZhNxCWyPqdAOGM2fAjbl85xaBW+QMMcQYwqNRLzq3guMLLQ0/z7GS/zTeDkRFfGtEhfwLk1FzdLTfvybJ2z+j5WHKuFy8DuwDVqFcznAwdKvHFZ/2liaNbULwZzMwBrWODW58=,iv:SHNnleF66rTCPPVFwFSHgfijRPr3YH3rZNFlivqAhPY=,tag:70jRA6mU9h4WczEKm88I9Q==,type:str]
    version: 3.13.3
